onClipEvent(load){
     function setbar()
     {
          bar._yscale = 100 * (_root.campaignData.technology[orig]() / maxLevel);
          if(maxLevel == _root.campaignData.technology[orig]())
          {
               plus._visible = false;
          }
     }
     var description = "+2 gold/second generated by castle";
     var heading = "Castle income upgrade";
     var price = 100;
     var effect = "setCastleIncome";
     var orig = "getCastleIncome";
     var maxLevel = 4;
     setbar();
}
